# Leave this out if using subdirectories in path. It causes issues with toCSS.
# baseURL: 'http://example.org/'
relativeURLs: true
languageCode: en
title: Example Resume
theme: hugo-devresume-theme
params:
  author: CowboySmall
  description: DevResume - Bootstrap 4 Resume/CV Template For Software Developers
  primaryColor: '#54B689'
  textPrimaryColor: '#292929'
  profile:
    enable: true
    name: Mitchell Bell
    tagline: IT Specialist
    avatar: avatar.jpg
  contact:
    enable: true
    location: Scottsboro
    list:
      # - icon: fas fa-phone-square
        # url: 'tel:#'
        # text: 0123 4567 87
      - icon: fas fa-envelope-square
        url: 'mailto:#'
        text: mbell0629@mail.nacc.edu
      - icon: fas fa-globe
        url: '#'
        text: https://github.com/mbell0629
  skills:
    enable: true
    list:
      - title: Technical
        items:
          - details: JavaScript/HTML
          - details: Python/Linux/C++
          - details: Hardware setup and repair
          - details: Diagnose and debug complex software problems
      - title: Professional
        items:
          - details: Effective communication
          - details: Dependable
          - details: Willing to learn
          - details: Good time management
  education:
    enable: true
    list:
      - degree: AAS in Computer Information Systems
        university: Northeast Alabama Community College
        dates: 2017-2021

  awards:
    enable: true
    list:
      - name: CompTIA+
        body: 
        date: '2019'
      - name: Google IT Specialist
        body: 
        date: '2020'
  languages:
    enable: false
    list:
      - name: English
        level: Native
      - name: Spanish
        level: Professional
  interests:
    enable: true
    list:
      - name: Hiking
      - name: Kayaking
      - name: Family
      - name: Nature Photography
  summary:
    enable: true
    text: >-
            Entry-level IT Specialist graduating in 2021 with a degree in Computer
            Information Systems. Highly motivated and does best in a progressive
            environment. Critical thinker who has a very high aptitude of complex
            problem solving. 
  experience:
    enable: true
    list:
      - title: Help Desk (IT)
        dates: 2015 - Present
        company: TechFour
        details: >-
          Handled all incoming calls from clients involving hardware and software issues.
          Forged community connections benefiting staff, clients, and families. Helped build
          the company from the beginning stages of planning.

      - title: Office assistant
        dates: 2014-2015
        company: The Truss Company
        details: >-
          Handled all incoming calls with clients. Designed house trusses with CAD software.
          Handled all clerical duties.

  projects:
    enable: false
    list:
      - title: Project Lorem Ipsum
        meta: Open Source
        tagline: >-
          You can use this section for your side projects. Lorem ipsum dolor sit
          amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
          Aenean massa. Cum sociis natoque penatibus et magnis dis parturient
          montes, nascetur ridiculus mus.
      - title: Project Sed Fringilla
        meta: Open Source
        tagline: >-
          You can use this section for your side projects. Cras dapibus. Vivamus
          elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo
          ligula, porttitor eu, consequat vitae, eleifend ac, enim.
      - title: Project Praesent
        meta: Open Source
        tagline: >-
          You can use this section for your side projects. Cras dapibus. Vivamus
          elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo
          ligula, porttitor eu, consequat vitae, eleifend ac, enim.
  information:
    enable: false
    list:
      - title: Papers
        items:
          - details: 2018 · Lorem Ipsum
          - details: 2016 · Sed Fringilla
      - title: Interests
        details: 'Climbing, Snowboarding, Photography, Travelling'
  social:
    enable: true
    list:
      - icon: fab fa-github-square
        url: https://github.com/mbell0629
        title: mbell0629
      # - icon: fab fa-linkedin
        # url: //linkedin.com/in/username
        # title: username
      # - icon: fab fa-twitter-square
        # url: //twitter.com/username
        # title: '@username'
  footer:
    copyright: Mitchell Bell
